pub const REGION: &str = "eu-central-1";
pub const DATA_BUCKET: &str = "bucket";
pub const DATA_PREFIX: &str = "prefix"; // prefix for parquet
pub const PRESIGNED_TIMEOUT: u64 = 3600; // url is available for 1 hour
pub const MAX_ROWS: u64 = 1000;
pub const CLUSTER: &str = "cluster";
pub const SUBNETS: [&str; 2] = ["foo", "bar"];
pub const SECURITY_GROUPS: [&str; 1] = ["sg-foo"];
pub const CONTAINER_NAME: &str = "foo";
pub const TASK_NAME: &str = "bar";
